# -*- coding: utf-8 -*-
"""
Created on 2022-10-14 15:49:29
---------
@summary:
---------
@author: 王火龙
"""

from feapder import Item


class YqLiuyanbanItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i yq_liuyanban
    """

    __table_name__ = "yq_liuyanban"

    def __init__(self, *args, **kwargs):
        # self.id = None  # 主键id
        self.url = None  # 文章地址
        self.title = None  # 标题
        self.pub_time = None  # 发布时间
        self.content = None  # 正文
        self.download_time = None  # 下载时间
        self.site = None  # 信源名
        self.site_id = None  # 信源id
        self.aid = None  # 唯一id
        # self.push_state = 0  # 推送状态
