# -*- coding: utf-8 -*-
"""
Created on 2022-10-13 15:58:41
---------
@summary:
---------
@author: 王火龙
"""

from feapder import Item


class TYcItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i t_yc
    """

    __table_name__ = "t_yc"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.name = None
        self.price = None
