# -*- coding: utf-8 -*-
"""
Created on 2022-10-13 15:07:51
---------
@summary:
---------
@author: 王火龙
"""

from feapder import Item


class ArticleListTiebaArticleItem(Item):
    """
    This class was generated by feapder
    command: feapder create -i article_list_tieba_article
    """

    __table_name__ = "article_list_tieba_article"

    def __init__(self, *args, **kwargs):
        # self.id = None
        self.title = None  # 标题
        self.url = None  # 帖子地址
        self.author = None  # 作者
        self.pub_time = None  # 发布时间
        self.download_time = None  # 下载时间
        self.author_url = None  # 用户首页
        self.author_head_portrait = None  # 用户头像地址
        self.content = None  # 发布内容
        self.aid = None  # 唯一id
        # self.spid = 0  # 回复关联帖子的id


